config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'attachments/destroy'
  devise_for :users

  root to: "posts#index"

  resources :posts do
    resources :comments, only: :create
  end

  get 'about', to: 'static_pages#about'
  resources :attachments, only: :destroy
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true

  scope :sorted, -> { order(created_at: :asc) }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, -> { sorted }, dependent: :destroy
  belongs_to :user

  has_many_attached :images

  validates :title, uniqueness: true
  validates :title, :description, :body, length: { minimum: 3 }, allow_nil: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def author_of?(resource)
    resource.user_id == self.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :find_attachment, only: :destroy

  def destroy
    @attachment.purge if current_user&.author_of?(@attachment.record)
  end

  private

  def find_attachment
    @attachment = ActiveStorage::Attachment.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @new_comment = current_user&.comments&.build(comment_params)
    @post = @new_comment.post

    if @new_comment&.save
      @new_comment.broadcast_append_to @new_comment.post, locals: { current_user: current_user }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_post, only: %i[show edit update destroy]

  def index
    @pagy, @posts = pagy(Post.with_attached_images.all.order(updated_at: :desc))
  end

  def show
    @comments = @post.comments.sorted
    @new_comment = current_user&.comments&.build
  end

  def new
    @post ||= Post.new
  end

  def edit; end

  def create
    @post ||= current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Your post successfully created'
    else
      flash.now[:alert] = 'Post was not created'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: 'Your post successfully updated'
    else
      flash.now[:alert] = 'Post was not updated'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: 'Post was successfully deleted'
    else
      redirect_to post_path(@post), notice: 'Post was not deleted'
    end
  end

  private

  def load_post
    @post ||= Post.with_attached_images.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :body, images: [])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  ALERTS = {
    notice: 'info',
    error: 'danger',
    success: 'success',
    alert: 'warning'
  }.freeze

  def flash_to_alert(flash)
    ALERTS[flash.to_sym]
  end

  def representable_any(files)
    selected_files = files&.select(&:representable?)
    selected_files.any? ? selected_files.first : false
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def format_time(updated_at_time)
    updated_at_time.strftime('%T')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attachments/destroy.js.erb
$('.attachment-<%= @attachment.id %>').remove();
<% if @attachment.destroyed? %>
  $('.notice').text('').append('attachment was successfully deleted.');
<% end %>

app/views/comments/_comment.html.slim
-if comment.user == current_user
  .card.border-success.mb-3.ms-auto.text-end.comment style="max-width: 20rem;" class="comment-#{comment.id}"
    .card-body.text-dark
      p class="card-text" = comment.body
    .card-footer.bg-transparent.border-success
      small class="text-muted" = 'by ' + comment.user.email
      br
      small class="text-muted" = 'at ' + format_time(comment.updated_at)
- else
  .card.border-dark.mb-3 style="max-width: 20rem;" class="comment-#{comment.id}"
    .card-body.text-dark
      p class="card-text" = comment.body
    .card-footer.bg-transparent.border-dark
      small class="text-muted" = 'by ' + comment.user.email
      br
      small class="text-muted" = 'at ' + format_time(comment.updated_at)

app/views/comments/_form.html.slim
  .new-comment.container.text-center.card.col-6.pt-3
    = form_with model: [@post, @new_comment] do |f|

      = render 'shared/errors', resource: @new_comment

      .row.g-3.align-items-center
        .col-12
          = f.text_field :body, class: "form-control", autofocus: true, placeholder: "Write new comment here"

      = f.hidden_field :post_id, value: @post.id

      .d-grid.gap-2.col-6.mx-auto.mt-3
        = f.submit 'Send comment', class: "btn btn-outline-success"

app/views/comments/create.turbo_stream.slim
- if @new_comment.errors.any?
  = turbo_stream.update 'new_comment' do
    = render 'comments/form', new_comment: @new_comment

app/views/layouts/application.html.slim
html
  head
    title DrupalTestPostsApp
    meta [charset="utf-8"]
    meta [name="viewport" content="width=device-width, initial-scale=1, shrink-to-fi=no"]
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

  body
    = render 'shared/nav'
    .container
      = render 'shared/flash'
      = yield

app/views/posts/_form.html.slim
.new-post.container.text-center.card.col-6.pt-3
  = form_with model: @post, local: true do |f|
    = render 'shared/errors', resource: @post

    .row.g-3.align-items-center
      .col-3
        = f.label :title, class: "col-form-label"
      .col-9
        = f.text_field :title, class: "form-control", autofocus: true, placeholder: "Write title here", autocomplete: "title"

    .row.g-3.align-items-center
      .col-3
        = f.label :description, class: "col-form-label"
      .col-9
        = f.text_field :description, class: "form-control", placeholder: "Some description please", autocomplete: "description"

    .row.g-3.align-items-center
      .col-3
        = f.label :body, class: "col-form-label"
      .col-9
        = f.text_area :body, class: "form-control", placeholder: "Tell us something", autocomplete: "body"

    .row.g-3.align-items-center
      .col-3
        = f.label :images, class: "col-form-label"
      .col-9
        = f.file_field :images, multiple: true, class: "form-control"

    - if current_user&.author_of?(@post)
      - if @post.images.attached?
        - @post.images.each do |file|
          . class="attachment-#{file.id}"
            p = link_to file.filename.to_s, url_for(file)
            = link_to 'Del', attachment_path(file), method: :delete, data: { turbo_method: :delete }, local: false, remote: true

    .d-grid.gap-2.col-6.mx-auto.mt-3
      = f.submit 'Publish post', class: "btn btn-outline-success"

app/views/posts/_post.html.slim
.col
  =link_to post, class: 'text-decoration-none'
    .card.text-center
      - if representable_any(post.images)
        = image_tag representable_any(post.images).representation(resize_to_limit: [300, 300]), class: "card-img-top"
      - else
        img src="..." class="card-img-top" alt="..."
      .card-body
        h5 class="card-title" style="color: black" = post.title
        p class="card-text" style="color: gray" = post.description
      .card-footer
        small class="text-muted" = time_ago_in_words(post.updated_at, include_seconds: false) + ' ago'

app/views/posts/edit.html.slim
.d-grid.gap-2.col-6.mx-auto.mt-3.mb-3
  =link_to 'To all posts', posts_path, class: "btn btn-outline-secondary mb-3"

= render 'form'

.d-grid.gap-2.col-6.mx-auto.mb-3.mt-3
  = link_to 'Delete post', post_path(@post), method: :delete, data: { turbo_method: :delete }, class: "btn btn-outline-danger mb-3"

app/views/posts/index.html.slim
== render partial: 'shared/pagy', locals: {pagy: @pagy}
.posts-list.mt-3
  .card-group
    .row.row-cols-1.row-cols-md-3.g-4
      - @posts.each do |post|
        =render post

app/views/posts/new.html.slim
.d-grid.gap-2.col-6.mx-auto.mt-3.mb-3
  =link_to 'To all posts', posts_path, class: "btn btn-outline-secondary mb-3"

= render 'form'

app/views/posts/show.html.slim
.d-grid.gap-2.col-6.mx-auto.mt-3
  =link_to 'To all posts', posts_path, class: "btn btn-outline-secondary mb-3"

.card.mb-3.text-center
  - if representable_any(@post.images)
    = image_tag representable_any(@post.images).representation(resize_to_limit: [1920, 1080]), class: "card-img-top"
  - else
    img src="..." class="card-img-top" alt=""
  .card-body
    h5 class="card-title" = @post.title
    p class="card-text"
      strong = @post.description
    p class="card-text" = @post.body
    p class="card-text"
      small class="text-muted" = time_ago_in_words(@post.updated_at, include_seconds: false) + ' ago'

- if @post.user == current_user
  .d-grid.gap-2.col-6.mx-auto
    =link_to 'Edit post', edit_post_path(@post), class: "btn btn-outline-warning mb-3"

= turbo_stream_from @post

.row
  .col-3
  div class="post-#{@post.id}-comments row col-6"
    = turbo_frame_tag :comments do
      = render @comments

- if user_signed_in?
  = turbo_frame_tag :new_comment do
    = render 'comments/form', new_comment: @new_comment

app/views/shared/_auth.html.slim
div.collapse.navbar-collapse id="navbarSupportedContent"
  ul.navbar-nav.ms-auto.mb-2.mb-lg-0
    li.nav-item.dropdown
      a.nav-link.dropdown-toggle.active href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"
        <i class="bi bi-person-lines-fill user-icon"></i>
      ul.dropdown-menu.dropdown-menu-dark.dropdown-menu-end
        - if user_signed_in?
          li
            = link_to current_user.email, edit_user_registration_path, class: "dropdown-item"
          li
            hr.dropdown-divider
          li
            = link_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "dropdown-item"
        - else
          li
            = link_to 'Sign in', new_user_session_path, class: "dropdown-item"
          li
            hr.dropdown-divider
          li
            = link_to 'Sign up', new_user_registration_path, class: "dropdown-item"
          li

app/views/shared/_errors.html.slim
div class="#{resource.class.name.downcase}-errors-#{resource.id} text-center"
  - if resource&.errors.present?
    ul
      - resource.errors.full_messages.each do |message|
        div role="alert" class = "alert alert-danger alert-dismissible fade show"
          strong = sanitize(message)
          button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  div role="alert" class = "alert alert-#{flash_to_alert(key)} alert-dismissible fade show mt-3"
    strong = sanitize(message)
    button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-md.navbar-light.bg-gradient style="--bs-bg-opacity: .7; background-color: #E8A87C;"
  div.container-fluid
    = link_to 'Tests app', posts_path, class: "navbar-brand"
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    div.collapse.navbar-collapse id="navbarSupportedContent"
      ul.navbar-nav.mr-auto.mb-2.mb-lg-0
        li.nav-item
          =link_to 'New post', new_post_path, class: 'nav-link active'
        li.nav-item
          =link_to 'About', about_path, class: 'nav-link'
    = render "shared/auth"

app/views/shared/_pagy.html.slim
/ This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
/ calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
/ The link variable is set to a proc that returns the link tag.
/ Usage: link.call( page_number [, text [, extra_attributes_string ]])
- link = pagy_link_proc(pagy, link_extra: 'class="page-link"')
.row
  .col-1.col-md-3
  nav.pagy-bootstrap-nav.col-6 role="navigation"

    ul.pagination.mt-3.justify-content-center

      - if pagy.prev
        li.page-item.prev == link.call(pagy.prev, "&lsaquo; Prev", 'aria-label="previous"')
      - else
        li.page-item.prev.disabled
          a.page-link href="#" == "&lsaquo; Prev"

      - pagy.series.each do |item|                 # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
        - if item.is_a?(Integer)                   # page link
          li.page-item == link.call(item)

        - elsif item.is_a?(String)                 # current page
          li.page-item.active == link.call(item)

        - elsif item == :gap                       # page gap
          li.page-item.disabled.gap
            a.page-link href="#" == "&hellip;"

      - if pagy.next
        li.page-item.next == link.call(pagy.next, "Next &rsaquo;", 'aria-label="next"')
      - else
        li.page-item.next.disabled
          a.page-link href="#" == "Next &rsaquo;"

  nav.pagy-bootstrap-nav.col-3 role="navigation"
    ul.pagination.pagination-sm.mt-3.justify-content-end
      li.page-item
        a.page-link.disabled href="#" Show by:
      li.page-item
        = link_to_unless_current('9', posts_path(items: 9), class: 'page-link') do
          = link_to '9', posts_path(items: 9), class: 'page-link active'
      li.page-item
        = link_to_unless_current('15', posts_path(items: 15), class: 'page-link') do
          = link_to '15', posts_path(items: 9), class: 'page-link active'
      li.page-item
        = link_to_unless_current('30', posts_path(items: 30), class: 'page-link') do
          = link_to '30', posts_path(items: 9), class: 'page-link active'
      li.page-item
        = link_to_unless_current('60', posts_path(items: 60), class: 'page-link') do
          = link_to '60', posts_path(items: 9), class: 'page-link active'

app/views/static_pages/about.html.slim
h1 About page
p This is test app for Drupal